import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets" / "onset_stress_b"
MODEL_DIR = ASSET_DIR / "models"


def write_obj(path: Path, vertices, faces):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# generated by generate_onset_stress_b_assets.py\n")
        for x, y, z in vertices:
            f.write(f"v {x:.9f} {y:.9f} {z:.9f}\n")
        for i, j, k in faces:
            f.write(f"f {i} {j} {k}\n")


def add_cap(faces, center_index, ring_start, segments, reverse=False):
    for s in range(segments):
        a = ring_start + s
        b = ring_start + ((s + 1) % segments)
        if reverse:
            faces.append((center_index, b, a))
        else:
            faces.append((center_index, a, b))


def make_cylinder(radius, half_thickness, segments, center_x=0.0, center_y=0.0, center_z=0.0):
    vertices = []
    faces = []

    for z_sign in (-1.0, 1.0):
        z = center_z + z_sign * half_thickness
        for s in range(segments):
            theta = 2.0 * math.pi * s / segments
            x = center_x + radius * math.cos(theta)
            y = center_y + radius * math.sin(theta)
            vertices.append((x, y, z))

    bottom_center_index = len(vertices) + 1
    vertices.append((center_x, center_y, center_z - half_thickness))
    top_center_index = len(vertices) + 1
    vertices.append((center_x, center_y, center_z + half_thickness))

    bottom_start = 1
    top_start = 1 + segments

    for s in range(segments):
        b0 = bottom_start + s
        b1 = bottom_start + ((s + 1) % segments)
        t0 = top_start + s
        t1 = top_start + ((s + 1) % segments)
        faces.append((b0, b1, t1))
        faces.append((b0, t1, t0))

    add_cap(faces, bottom_center_index, bottom_start, segments, reverse=True)
    add_cap(faces, top_center_index, top_start, segments, reverse=False)
    return vertices, faces


def main():
    params = {
        "cam_radius": 0.030,
        "cam_eccentricity": 0.006,
        "cam_thickness": 0.020,
        "roller_radius": 0.010,
        "roller_thickness": 0.018,
        "cam_segments": 160,
        "roller_segments": 128,
        "phase": math.pi,
        "cam_init_pos": [0.0, 0.0, 0.0],
        "motor_joint_pos": [0.0, 0.0, 0.0],
        "gravity_y": 0.0,
        "density": 7800.0,
        "friction": 0.0,
        "restitution": 0.0,
        "motor_speed": -2.0,
        "step_size": 0.001,
        "total_time": 0.45,
        "target_onset_time": 0.15,
        "dynamics_substeps": 32,
    }

    cam_half_t = 0.5 * params["cam_thickness"]
    roller_half_t = 0.5 * params["roller_thickness"]
    center_x = params["cam_eccentricity"] * math.cos(params["phase"])
    center_y = params["cam_eccentricity"] * math.sin(params["phase"])

    cam_vertices, cam_faces = make_cylinder(
        params["cam_radius"],
        cam_half_t,
        params["cam_segments"],
        center_x=center_x,
        center_y=center_y,
        center_z=0.0,
    )
    roller_vertices, roller_faces = make_cylinder(
        params["roller_radius"],
        roller_half_t,
        params["roller_segments"],
        center_x=0.0,
        center_y=0.0,
        center_z=0.0,
    )

    onset_theta = params["phase"] + params["motor_speed"] * params["target_onset_time"]
    reach = params["cam_radius"] + params["roller_radius"]
    onset_y = (
        params["cam_eccentricity"] * math.sin(onset_theta)
        + math.sqrt(max(reach * reach - (params["cam_eccentricity"] * math.cos(onset_theta)) ** 2, 0.0))
    )
    params["follower_init_pos"] = [0.0, onset_y, 0.0]
    params["preload_anchor_pos"] = [0.0, 0.0, 0.0]
    params["preload_rest_length"] = onset_y
    params["preload_stiffness"] = 680.0
    params["preload_damping"] = 50.0

    write_obj(MODEL_DIR / "onset_cam.obj", cam_vertices, cam_faces)
    write_obj(MODEL_DIR / "roller_follower.obj", roller_vertices, roller_faces)

    metadata_path = ASSET_DIR / "onset_stress_b_model.json"
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    with metadata_path.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(params, f, indent=2)
        f.write("\n")

    print(f"Wrote {MODEL_DIR / 'onset_cam.obj'}")
    print(f"Wrote {MODEL_DIR / 'roller_follower.obj'}")
    print(f"Wrote {metadata_path}")


if __name__ == "__main__":
    main()
